import { useState, useEffect } from "react";
import { getPatientScribeSessions } from "../../lib/aiScribeDb";

export default function EHRScribeNotes({ patientId, patientChartId }) {
  const [sessions, setSessions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [expandedNote, setExpandedNote] = useState(null);

  useEffect(() => {
    loadSessions();
  }, [patientId]);

  const loadSessions = async () => {
    if (!patientId) return;
    
    setLoading(true);
    const { data, error } = await getPatientScribeSessions(patientId);
    setLoading(false);

    if (!error && data) {
      // Sort by date, most recent first
      const sorted = data.sort((a, b) => 
        new Date(b.date_of_service) - new Date(a.date_of_service)
      );
      setSessions(sorted);
    }
  };

  if (loading) {
    return (
      <div style={{
        background: "var(--glass2)",
        border: "1px solid var(--border)",
        borderRadius: 20,
        padding: "2rem",
        textAlign: "center"
      }}>
        <div style={{
          width: 40,
          height: 40,
          border: "4px solid var(--border)",
          borderTopColor: "var(--purple)",
          borderRadius: "50%",
          margin: "0 auto 1rem",
          animation: "spin 1s linear infinite"
        }} />
        <style>{`
          @keyframes spin {
            to { transform: rotate(360deg); }
          }
        `}</style>
        <p style={{ color: "var(--muted)", fontSize: 14 }}>Loading AI Scribe notes...</p>
      </div>
    );
  }

  if (sessions.length === 0) {
    return (
      <div style={{
        background: "var(--glass2)",
        border: "1px solid var(--border)",
        borderRadius: 20,
        padding: "2rem",
        textAlign: "center"
      }}>
        <div style={{ fontSize: 48, marginBottom: "1rem" }}>🎙️</div>
        <h3 style={{ fontSize: 16, fontWeight: 600, marginBottom: "0.5rem" }}>
          No AI Scribe Notes Yet
        </h3>
        <p style={{ color: "var(--muted)", fontSize: 14 }}>
          Clinical notes generated by AI Scribe will appear here
        </p>
      </div>
    );
  }

  return (
    <div style={{
      background: "var(--glass2)",
      border: "1px solid var(--border)",
      borderRadius: 20,
      padding: "1.5rem"
    }}>
      <div style={{
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: "1.5rem"
      }}>
        <div>
          <h3 style={{ fontSize: 18, fontWeight: 600, marginBottom: "0.25rem" }}>
            🎙️ AI Scribe Notes
          </h3>
          <p style={{ color: "var(--muted)", fontSize: 13 }}>
            {sessions.length} session{sessions.length !== 1 ? 's' : ''} documented
          </p>
        </div>
        <div style={{
          background: "rgba(124,111,247,0.2)",
          border: "1px solid rgba(124,111,247,0.3)",
          borderRadius: 12,
          padding: "0.5rem 1rem",
          fontSize: 12,
          color: "var(--lavender)"
        }}>
          AI-Generated
        </div>
      </div>

      {/* Sessions List */}
      <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
        {sessions.map(session => (
          <div
            key={session.id}
            style={{
              background: "rgba(255,255,255,0.04)",
              border: "1px solid var(--border)",
              borderRadius: 16,
              overflow: "hidden",
              transition: "all 0.2s"
            }}
          >
            {/* Session Header */}
            <div
              onClick={() => setExpandedNote(expandedNote === session.id ? null : session.id)}
              style={{
                padding: "1rem 1.25rem",
                cursor: "pointer",
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
                background: expandedNote === session.id ? "rgba(124,111,247,0.1)" : "transparent"
              }}
            >
              <div style={{ flex: 1 }}>
                <div style={{ display: "flex", alignItems: "center", gap: "0.75rem", marginBottom: "0.5rem" }}>
                  <div style={{ fontSize: 14, fontWeight: 600 }}>
                    {new Date(session.date_of_service).toLocaleDateString('en-US', {
                      month: 'short',
                      day: 'numeric',
                      year: 'numeric'
                    })}
                  </div>
                  <div style={{
                    fontSize: 11,
                    padding: "2px 8px",
                    borderRadius: 12,
                    background: session.status === 'pushed_to_ehr' ? 'rgba(78,205,196,0.2)' : 'rgba(124,111,247,0.2)',
                    color: session.status === 'pushed_to_ehr' ? 'var(--teal)' : 'var(--lavender)'
                  }}>
                    {session.status === 'pushed_to_ehr' ? '✓ In EHR' : session.status}
                  </div>
                  {session.quality_score && (
                    <div style={{
                      fontSize: 11,
                      padding: "2px 8px",
                      borderRadius: 12,
                      background: "rgba(245,200,66,0.2)",
                      color: "var(--gold)"
                    }}>
                      Quality: {session.quality_score}%
                    </div>
                  )}
                </div>
                <div style={{ fontSize: 12, color: "var(--muted)" }}>
                  {session.session_type} • {session.modality} • {session.provider_name}
                  {session.duration_minutes && ` • ${session.duration_minutes} min`}
                </div>
              </div>
              <div style={{
                fontSize: 20,
                color: "var(--muted)",
                transform: expandedNote === session.id ? "rotate(180deg)" : "rotate(0deg)",
                transition: "transform 0.2s"
              }}>
                ▼
              </div>
            </div>

            {/* Expanded Note Content */}
            {expandedNote === session.id && (
              <div style={{
                padding: "1.25rem",
                borderTop: "1px solid var(--border)",
                background: "rgba(0,0,0,0.2)"
              }}>
                {/* Clinical Context */}
                {session.clinical_context && (
                  <div style={{ marginBottom: "1.5rem" }}>
                    <div style={{
                      fontSize: 11,
                      fontWeight: 600,
                      textTransform: "uppercase",
                      letterSpacing: "0.05em",
                      color: "var(--muted2)",
                      marginBottom: "0.5rem"
                    }}>
                      Clinical Context
                    </div>
                    <div style={{
                      fontSize: 13,
                      color: "var(--muted)",
                      lineHeight: 1.6,
                      padding: "0.75rem",
                      background: "rgba(255,255,255,0.03)",
                      borderRadius: 8
                    }}>
                      {session.clinical_context}
                    </div>
                  </div>
                )}

                {/* ICD-10 Codes */}
                {session.icd10_codes && session.icd10_codes.length > 0 && (
                  <div style={{ marginBottom: "1.5rem" }}>
                    <div style={{
                      fontSize: 11,
                      fontWeight: 600,
                      textTransform: "uppercase",
                      letterSpacing: "0.05em",
                      color: "var(--muted2)",
                      marginBottom: "0.5rem"
                    }}>
                      ICD-10 Codes
                    </div>
                    <div style={{ display: "flex", flexWrap: "wrap", gap: "0.5rem" }}>
                      {session.icd10_codes.map((code, idx) => (
                        <div
                          key={idx}
                          style={{
                            fontSize: 11,
                            padding: "4px 10px",
                            borderRadius: 8,
                            background: "rgba(78,205,196,0.2)",
                            color: "var(--teal)",
                            border: "1px solid rgba(78,205,196,0.3)"
                          }}
                        >
                          {code}
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Generated Note */}
                {session.generated_note && (
                  <div>
                    <div style={{
                      fontSize: 11,
                      fontWeight: 600,
                      textTransform: "uppercase",
                      letterSpacing: "0.05em",
                      color: "var(--muted2)",
                      marginBottom: "0.5rem"
                    }}>
                      Clinical Note
                    </div>
                    <div style={{
                      fontSize: 13,
                      lineHeight: 1.8,
                      color: "var(--white)",
                      whiteSpace: "pre-wrap",
                      fontFamily: "monospace",
                      padding: "1rem",
                      background: "rgba(0,0,0,0.3)",
                      borderRadius: 8,
                      maxHeight: 400,
                      overflowY: "auto"
                    }}>
                      {session.generated_note}
                    </div>
                  </div>
                )}

                {/* Actions */}
                <div style={{
                  display: "flex",
                  gap: "0.5rem",
                  marginTop: "1rem",
                  paddingTop: "1rem",
                  borderTop: "1px solid var(--border)"
                }}>
                  <button
                    onClick={() => {
                      navigator.clipboard.writeText(session.generated_note);
                      alert('Note copied to clipboard!');
                    }}
                    style={{
                      flex: 1,
                      padding: "0.5rem",
                      borderRadius: 8,
                      border: "1px solid var(--border)",
                      background: "rgba(124,111,247,0.1)",
                      color: "var(--lavender)",
                      fontSize: 12,
                      cursor: "pointer"
                    }}
                  >
                    📋 Copy Note
                  </button>
                  <button
                    onClick={() => {
                      const blob = new Blob([session.generated_note], { type: 'text/plain' });
                      const url = URL.createObjectURL(blob);
                      const a = document.createElement('a');
                      a.href = url;
                      a.download = `note-${session.patient_id}-${session.date_of_service}.txt`;
                      a.click();
                      URL.revokeObjectURL(url);
                    }}
                    style={{
                      flex: 1,
                      padding: "0.5rem",
                      borderRadius: 8,
                      border: "1px solid var(--border)",
                      background: "rgba(78,205,196,0.1)",
                      color: "var(--teal)",
                      fontSize: 12,
                      cursor: "pointer"
                    }}
                  >
                    ⬇️ Download
                  </button>
                </div>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
